language: node_js

os:
  - linux

cache:
  directories:
    - node_modules

node_js:
  - 12
  - 10

install:
  - npm install
  - npm run snyk

before_script:
  - npm run lint
  - npm run build

script:
  - npm test
