language: node_js

os:
  - linux

jobs:
  include:
    - stage: Testing (node 12)
      node_js: 12
      if: type = pull_request
      before_script:
        - yarn lint
        - yarn build
      install:
        - yarn
        - yarn snyk
      script:
        - yarn test
    - stage: Testing (node 10)
      node_js: 10
      if: type = pull_request
      before_script:
        - yarn lint
        - yarn build
      install:
        - yarn
        - yarn snyk
      script:
        - yarn test
    - stage: release
      node_js: 12
      if: branch = master AND type = push
      script: skip
      deploy:
        provider: script
        cleanup: true
        script: yarn && yarn build && yarn semantic-release
